name: tesserapp
description: A new Flutter project.

dependencies:
  sprintf: ^4.0.0
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:

  fonts:
  - family: GeoNMS
    fonts:
    - asset: fonts/geonms.ttf

  uses-material-design: true
