name: pentachoron
description: A 4D geometry showcasing.

dependencies:
  sprintf: ^4.0.0
  url_launcher: ^3.0.3
  angles: ^1.0.0
  dynamic_theme: ^1.0.0
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:

  fonts:
  - family: GeoNMS
    fonts:
    - asset: fonts/geonms.ttf

  uses-material-design: true
